name: CustomServerUtil
authors: [Mayus, Pepe44, Ayley, Tallerik]
version: 1.0
main: customserverutil.CustomServerUtil
softdepend: [PermissionsEx]
commands:
    c:
        description: Creative mode
    s:
        description: Survival mode
    sp:
        description: Spectator mode
    sethome:
        description: Setzt ein Home.
        usage: "/sethome <name>"
    home:
        description: Wenn 1. Argument Name ist, dann TP; wenn 1. Argument 'list' ist, dann Auflistung der Homes.
        usage: "/home <name/list>"
    sun:
        description: Clears the sky.
    day:
        description: Sets the daytime to 0.
    rlcfg:
        description: Reloads the config.
    server:
        description: Opens a gui for teleportation.
    mail:
        description: ruft deine Mails ab
    sendmail:
        description: Sendet einem Spieler eine Mail
    ban:
        description: Bannt einen Spieler
    pardon:
        description: Entbannt einen Spieler
    warn:
        description: Verwarnt einen Spieler
    nick:
        description: Gibt dir einen Nicknamen.
    ping:
        description: Zeigt deinen Ping an.
    warp:
        description: Bringt dich zu einem Warp
    setwarp:
        description: Setzt einen Warp
        usage: "/setwarp <Name> <Range>"
    removewarp:
        description: Entfernt einen Warp
    spawn:
        description: Bringt dich zum Warp 'spawn'.
    tpa:
        description: Sendet einem Spieler eine Teleportanfrage
    tpaccept:
        description: Akzeptiert eine Teleportanfrage
    tpdecline:
        description: Lehnt eine Teleportanfrage ab.
    spectateplayer:
        description: Nur interner Zugang!
    report:
        description: Reportet einen Spieler.
    build:
        description: Erlaubt dir das Bauen in einer Range eines Warps.
    friend:
        description: Alle Friend-Commands
    lobby:
        description: Send dich zur Lobby
        alias: [hub, h, leave]
    v:
        description: Makes your vanish
    money:
        description: Shows your current money.
        alias: eco
    transfer:
        description: Transfers money to your m8tes.
    setmoney:
        description: Sets the money of the specified Player.
    msg:
        description: Private Message
    r:
        description: Reply Private Message
    sell:
        description: sells to a buyer
    ddos:
        description: sth like antioch
    setlang:
        description: Sets the language for a player
    force:
        description: Forces a player to execute a command