name: CustomServerUtil
authors: [Mayus, Pepe44, Ayley, Tallerik]
version: 1.0
main: customserverutil.CustomServerUtil
softdepend: [PermissionsEx]
commands:
    c:
        description: Creative mode
    s:
        description: Survival mode
    sp:
        description: Spectator mode
    sethome:
        description: Setzt ein Home.
        usage: "/sethome <name>"
    home:
        description: Wenn 1. Argument Name ist, dann TP; wenn 1. Argument 'list' ist, dann Auflistung der Homes.
        usage: "/home <name/list>"
    sun:
        description: Clears the sky.
    day:
        description: Sets the daytime to 0.
    rlcfg:
        description: Reloads the config.
    server:
        description: Opens a gui for teleportation.
    mail:
        description: ruft deine Mails ab
    sendmail:
        description: Sendet einem Spieler eine Mail
    ban:
        description: Bannt einen Spieler
    pardon:
        description: Entbannt einen Spieler
    warn:
        description: Verwarnt einen Spieler
    nick:
        description: Gibt dir einen Nicknamen.
    ping:
        description: Zeigt deinen Ping an.
    warp:
        description: Bringt dich zu einem Warp
    setwarp:
        description: Setzt einen Warp
        usage: "/setwarp <Name> <Range>"
    removewarp:
        description: Entfernt einen Warp
    spawn:
        description: Bringt dich zum Warp 'spawn'.
